// <auto-generated />
using System;
using LicenseIssuanceService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicenseIssuanceService.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250710044725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LicenseIssuanceService.Model.LicenseIssuance", b =>
                {
                    b.Property<int>("LicenseIssuanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LicenseIssuanceID"));

                    b.Property<DateTime>("LicenseExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LicenseIssuerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LicenseIssuanceID");

                    b.ToTable("LicenseIssuance");
                });
#pragma warning restore 612, 618
        }
    }
}
